[package]
name = "jupiter-swap-api-client"
version = "0.1.0"
description = "Rust client for Jupiter Swap API integration."
license = "MIT"
edition = { workspace = true }
readme = "README.md"

[dependencies]
anyhow = "1"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
solana-sdk = { workspace = true }
base64 = "0.21"
serde_qs = "0.12.0"
reqwest = { version = "0.11.20", features = ["json"] }
